PRAGMA foreign_keys=OFF;
INSERT INTO characters VALUES(1,'https://rickandmortyapi.com/api/character/avatar/1.jpeg','Rick Sanchez','Human','Alive',1);
INSERT INTO characters VALUES(2,'https://rickandmortyapi.com/api/character/avatar/2.jpeg','Morty Smith','Human','Alive',1);
INSERT INTO characters VALUES(3,'https://rickandmortyapi.com/api/character/avatar/3.jpeg','Summer Smith','Human','Alive',1);
INSERT INTO characters VALUES(4,'https://rickandmortyapi.com/api/character/avatar/4.jpeg','Beth Smith','Human','Alive',0);
INSERT INTO characters VALUES(5,'https://rickandmortyapi.com/api/character/avatar/5.jpeg','Jerry Smith','Human','Alive',1);
INSERT INTO characters VALUES(6,'https://rickandmortyapi.com/api/character/avatar/6.jpeg','Abadango Cluster Princess','Alien','Alive',0);
INSERT INTO characters VALUES(7,'https://rickandmortyapi.com/api/character/avatar/7.jpeg','Abradolf Lincler','Human','unknown',0);
INSERT INTO characters VALUES(8,'https://rickandmortyapi.com/api/character/avatar/8.jpeg','Adjudicator Rick','Human','Dead',0);
INSERT INTO characters VALUES(9,'https://rickandmortyapi.com/api/character/avatar/9.jpeg','Agency Director','Human','Dead',0);
INSERT INTO characters VALUES(10,'https://rickandmortyapi.com/api/character/avatar/10.jpeg','Alan Rails','Human','Dead',0);
INSERT INTO characters VALUES(11,'https://rickandmortyapi.com/api/character/avatar/11.jpeg','Albert Einstein','Human','Dead',0);
INSERT INTO characters VALUES(12,'https://rickandmortyapi.com/api/character/avatar/12.jpeg','Alexander','Human','Dead',0);
INSERT INTO characters VALUES(13,'https://rickandmortyapi.com/api/character/avatar/13.jpeg','Alien Googah','Alien','unknown',0);
INSERT INTO characters VALUES(14,'https://rickandmortyapi.com/api/character/avatar/14.jpeg','Alien Morty','Alien','unknown',0);
INSERT INTO characters VALUES(15,'https://rickandmortyapi.com/api/character/avatar/15.jpeg','Alien Rick','Alien','unknown',0);
INSERT INTO characters VALUES(16,'https://rickandmortyapi.com/api/character/avatar/16.jpeg','Amish Cyborg','Alien','Dead',1);
INSERT INTO characters VALUES(17,'https://rickandmortyapi.com/api/character/avatar/17.jpeg','Annie','Human','Alive',1);
INSERT INTO characters VALUES(18,'https://rickandmortyapi.com/api/character/avatar/18.jpeg','Antenna Morty','Human','Alive',1);
INSERT INTO characters VALUES(19,'https://rickandmortyapi.com/api/character/avatar/19.jpeg','Antenna Rick','Human','unknown',0);
INSERT INTO characters VALUES(20,'https://rickandmortyapi.com/api/character/avatar/20.jpeg','Ants in my Eyes Johnson','Human','unknown',0);